version: '3'
services:
    nginx:
        image: nginx
        ports:
            - "9999:80"
        depends_on:
            - php
        volumes:
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:cached
    php:
        build: .
        volumes:
            - "./app:/app"
    pgsql:
        build: ./pgsql
        ports:
            - "5432:5432"
        volumes:
            - ./pgsql/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=example
    pgadmin:
        image: dpage/pgadmin4
        ports:
            - "5050:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=user@domain.com
            - PGADMIN_DEFAULT_PASSWORD=SuperSecret
