version: '3'
services:
    nginx:
        image: nginx
        ports:
            - "9000:80"
        depends_on:
            - php
        volumes:
            - "./app:/app"
            - ./nginx/site.conf:/etc/nginx/conf.d/default.conf:cached
    php:
        build: .
        volumes:
            - "./app:/app"
    pgsql:
        build: ./pgsql
        ports:
            - "5432:5432"
# Windowsの場合に権限エラーでDBが起動しない時は、開発環境でのデータ永続化を諦めて直下の２行（Volumes設定）をコメントアウトすることで、とりあえず動くはず
        volumes:
            - ./pgsql/data:/var/lib/postgresql/data
        environment:
            - POSTGRES_PASSWORD=example
    pgadmin:
        image: dpage/pgadmin4
        ports:
            - "5050:80"
        environment:
            - PGADMIN_DEFAULT_EMAIL=user@domain.com
            - PGADMIN_DEFAULT_PASSWORD=SuperSecret
